// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment.sql

package sqlc

import (
	"context"
)

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, amount, currency, status, refunded_amount FROM payments WHERE id = ?
`

func (q *Queries) GetPayment(ctx context.Context, id string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RefundedAmount,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, amount, currency, status, refunded_amount FROM payments WHERE order_id = ?
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID string) (Payment, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.RefundedAmount,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :exec
INSERT INTO payments (id, order_id, amount, currency, status, refunded_amount)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertPaymentParams struct {
	ID             string
	OrderID        string
	Amount         int64
	Currency       string
	Status         string
	RefundedAmount int64
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.ExecContext(ctx, insertPayment,
		arg.ID,
		arg.OrderID,
		arg.Amount,
		arg.Currency,
		arg.Status,
		arg.RefundedAmount,
	)
	return err
}

const updatePayment = `-- name: UpdatePayment :exec
UPDATE payments SET status = ?, refunded_amount = ? WHERE id = ?
`

type UpdatePaymentParams struct {
	Status         string
	RefundedAmount int64
	ID             string
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, updatePayment, arg.Status, arg.RefundedAmount, arg.ID)
	return err
}
