// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Order struct {
	ID            string
	CustomerID    string
	Status        string
	TotalAmount   int64
	TotalCurrency string
	PlacedAt      string
}

type OrderItem struct {
	ID                int64
	OrderID           string
	ProductID         string
	Quantity          int64
	UnitPriceAmount   int64
	UnitPriceCurrency string
}

type Payment struct {
	ID             string
	OrderID        string
	Amount         int64
	Currency       string
	Status         string
	RefundedAmount int64
}

type Product struct {
	ID    string
	Name  string
	Stock int64
}

type Reservation struct {
	ID        int64
	ProductID string
	OrderID   string
	Quantity  int64
}
