// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: order.sql

package db

import (
	"context"
)

const getOrder = `-- name: GetOrder :one
SELECT id, customer_id, status, total_amount, total_currency, placed_at FROM orders WHERE id = ?
`

func (q *Queries) GetOrder(ctx context.Context, id string) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.TotalAmount,
		&i.TotalCurrency,
		&i.PlacedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT id, order_id, product_id, quantity, unit_price_amount, unit_price_currency FROM order_items WHERE order_id = ?
`

func (q *Queries) GetOrderItems(ctx context.Context, orderID string) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPriceAmount,
			&i.UnitPriceCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders (id, customer_id, status, total_amount, total_currency, placed_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertOrderParams struct {
	ID            string
	CustomerID    string
	Status        string
	TotalAmount   int64
	TotalCurrency string
	PlacedAt      string
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.ExecContext(ctx, insertOrder,
		arg.ID,
		arg.CustomerID,
		arg.Status,
		arg.TotalAmount,
		arg.TotalCurrency,
		arg.PlacedAt,
	)
	return err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO order_items (order_id, product_id, quantity, unit_price_amount, unit_price_currency)
VALUES (?, ?, ?, ?, ?)
`

type InsertOrderItemParams struct {
	OrderID           string
	ProductID         string
	Quantity          int64
	UnitPriceAmount   int64
	UnitPriceCurrency string
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.ExecContext(ctx, insertOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPriceAmount,
		arg.UnitPriceCurrency,
	)
	return err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders SET status = ? WHERE id = ?
`

type UpdateOrderStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	return err
}
