// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product.sql

package sqlc

import (
	"context"
)

const deleteReservation = `-- name: DeleteReservation :exec
DELETE FROM reservations WHERE product_id = ? AND order_id = ?
`

type DeleteReservationParams struct {
	ProductID string
	OrderID   string
}

func (q *Queries) DeleteReservation(ctx context.Context, arg DeleteReservationParams) error {
	_, err := q.db.ExecContext(ctx, deleteReservation, arg.ProductID, arg.OrderID)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, stock FROM products WHERE id = ?
`

func (q *Queries) GetProduct(ctx context.Context, id string) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(&i.ID, &i.Name, &i.Stock)
	return i, err
}

const getReservations = `-- name: GetReservations :many
SELECT id, product_id, order_id, quantity FROM reservations WHERE product_id = ?
`

func (q *Queries) GetReservations(ctx context.Context, productID string) ([]Reservation, error) {
	rows, err := q.db.QueryContext(ctx, getReservations, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reservation
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.OrderID,
			&i.Quantity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProduct = `-- name: InsertProduct :exec
INSERT INTO products (id, name, stock) VALUES (?, ?, ?)
`

type InsertProductParams struct {
	ID    string
	Name  string
	Stock int64
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) error {
	_, err := q.db.ExecContext(ctx, insertProduct, arg.ID, arg.Name, arg.Stock)
	return err
}

const insertReservation = `-- name: InsertReservation :exec
INSERT INTO reservations (product_id, order_id, quantity) VALUES (?, ?, ?)
`

type InsertReservationParams struct {
	ProductID string
	OrderID   string
	Quantity  int64
}

func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) error {
	_, err := q.db.ExecContext(ctx, insertReservation, arg.ProductID, arg.OrderID, arg.Quantity)
	return err
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products SET name = ?, stock = ? WHERE id = ?
`

type UpdateProductParams struct {
	Name  string
	Stock int64
	ID    string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct, arg.Name, arg.Stock, arg.ID)
	return err
}
